"""
services/email_service.py
--------------------------
High-level email dispatch orchestration layer.

This is the glue between:
    - The risk agent's green_light decision
    - The recipient database
    - The SMTP sender tool

Called by:  crews/marketing_crew.py → run_email_campaign_pipeline()
"""

import logging
import json
from typing import Dict, Any

from database.recipients import get_recipients
from tools.smtp_email_sender import send_smtp_email

logger = logging.getLogger("email_service")


# ── HTML email template ───────────────────────────────────────────────────────

def _build_html_body(content_dict: Dict[str, Any], campaign_id: Any = None) -> str:
    """
    Convert a content_dict (from the content agent) into a professional HTML email.

    Supported keys in content_dict:
        email_subject       — used as the headline inside the email body
        email_body          — main body text (may contain newlines)
        instagram_caption   — appended as a social preview section (optional)
        twitter_post        — appended as a twitter preview section (optional)
    """
    subject_line = content_dict.get("email_subject", "Important Update from Our Team")
    body_text    = content_dict.get("email_body", "")
    campaign_ref = f"Campaign #{campaign_id}" if campaign_id else "Marketing Campaign"

    # Convert plain newlines to HTML paragraphs
    paragraphs = "".join(
        f"<p style='margin:0 0 16px 0;'>{line.strip()}</p>"
        for line in body_text.split("\n")
        if line.strip()
    ) or f"<p style='margin:0 0 16px 0;'>{body_text}</p>"

    # Optional social preview block
    social_html = ""
    if content_dict.get("instagram_caption") or content_dict.get("twitter_post"):
        ig  = content_dict.get("instagram_caption", "")
        twt = content_dict.get("twitter_post", "")
        social_rows = ""
        if ig:
            social_rows += (
                f"<tr><td style='padding:8px 0;'>"
                f"<strong>📸 Instagram:</strong> {ig}</td></tr>"
            )
        if twt:
            social_rows += (
                f"<tr><td style='padding:8px 0;'>"
                f"<strong>🐦 Twitter/X:</strong> {twt}</td></tr>"
            )
        social_html = f"""
        <table width="100%" cellpadding="0" cellspacing="0" style="
            background:#f0f4ff; border-radius:8px; padding:16px; margin-top:24px;">
          <tr><td style="font-weight:bold; color:#4f46e5; padding-bottom:8px;">
            📣 Social Media Preview
          </td></tr>
          {social_rows}
        </table>"""

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>{subject_line}</title>
</head>
<body style="margin:0; padding:0; background:#f9fafb; font-family:Arial,Helvetica,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0"
         style="background:#f9fafb; padding:40px 20px;">
    <tr><td align="center">
      <table width="600" cellpadding="0" cellspacing="0"
             style="background:#ffffff; border-radius:12px;
                    box-shadow:0 2px 8px rgba(0,0,0,.08); overflow:hidden;">

        <!-- Header -->
        <tr>
          <td style="background:linear-gradient(135deg,#4f46e5,#7c3aed);
                     padding:32px 40px; text-align:center;">
            <h1 style="color:#ffffff; font-size:22px; margin:0; font-weight:700;">
              Marketing AI Crew
            </h1>
            <p style="color:rgba(255,255,255,.8); font-size:13px; margin:8px 0 0 0;">
              {campaign_ref}
            </p>
          </td>
        </tr>

        <!-- Body -->
        <tr>
          <td style="padding:40px;">
            <h2 style="color:#1f2937; font-size:20px; margin:0 0 20px 0;">
              {subject_line}
            </h2>
            <div style="color:#374151; font-size:15px; line-height:1.7;">
              {paragraphs}
            </div>
            {social_html}
          </td>
        </tr>

        <!-- Footer -->
        <tr>
          <td style="background:#f3f4f6; padding:24px 40px; text-align:center;
                     border-top:1px solid #e5e7eb;">
            <p style="color:#9ca3af; font-size:12px; margin:0;">
              This email was generated by Marketing AI Crew &bull; Automated campaign system<br/>
              © 2026 Your Company. All rights reserved.
            </p>
          </td>
        </tr>

      </table>
    </td></tr>
  </table>
</body>
</html>"""


def _build_text_body(content_dict: Dict[str, Any]) -> str:
    """Build a plain-text fallback from the content dict."""
    parts = []
    if content_dict.get("email_subject"):
        parts.append(content_dict["email_subject"])
        parts.append("=" * len(content_dict["email_subject"]))
    if content_dict.get("email_body"):
        parts.append(content_dict["email_body"])
    if content_dict.get("instagram_caption"):
        parts.append(f"\nInstagram: {content_dict['instagram_caption']}")
    if content_dict.get("twitter_post"):
        parts.append(f"Twitter/X: {content_dict['twitter_post']}")
    parts.append("\n\nThis email was generated by Marketing AI Crew.")
    return "\n".join(parts)


# ── Main dispatch function ────────────────────────────────────────────────────

def dispatch_campaign_email(
    content_dict: Dict[str, Any],
    campaign_id: Any,
    risk_result: Dict[str, Any],
    campaign_type: str = None,
) -> Dict[str, Any]:
    """
    Orchestrate the end-to-end email campaign dispatch.

    Pipeline:
        1. Check risk_result["green_light"] — block immediately if False
        2. Fetch recipients from database/recipients.py
        3. Build HTML + plain-text email from content_dict
        4. Send via SMTP (one connection, loop over recipients)
        5. Return a structured summary dict

    Args:
        content_dict  : output from the content agent (email_subject, email_body, etc.)
        campaign_id   : identifier used for logging and email headers
        risk_result   : dict from run_risk_check() — must have "green_light" key
        campaign_type : optional filter passed to get_recipients()

    Returns:
        dict with keys:
            blocked      — bool  (True = emails were NOT sent due to risk)
            block_reason — str or None
            sent         — int  (number of successfully delivered emails)
            failed       — int  (number of failed sends)
            recipients   — int  (total attempted)
            success      — bool (True only if all sent with no failures)
    """

    # ── Step 1: Risk gate ──────────────────────────────────────────────────────
    green_light   = risk_result.get("green_light", False)
    block_reason  = risk_result.get("flag_reason") or risk_result.get("explanation", "")

    if not green_light:
        reason = (
            f"Risk check FAILED — green_light=False. "
            f"Reason: {block_reason or 'No reason provided.'} | "
            f"Scores — brand_safety: {risk_result.get('brand_safety')}, "
            f"legal_risk: {risk_result.get('legal_risk')}, "
            f"cultural_sensitivity: {risk_result.get('cultural_sensitivity')}"
        )
        logger.warning("🚫  Campaign %s BLOCKED. %s", campaign_id, reason)
        return {
            "blocked":      True,
            "block_reason": reason,
            "sent":         0,
            "failed":       0,
            "recipients":   0,
            "success":      False,
        }

    # ── Step 2: Fetch recipients ───────────────────────────────────────────────
    recipients = get_recipients(campaign_type=campaign_type)
    if not recipients:
        msg = (
            "No recipients found. "
            "Edit HARDCODED_RECIPIENTS in database/recipients.py to add email addresses."
        )
        logger.error(msg)
        return {
            "blocked":      False,
            "block_reason": None,
            "sent":         0,
            "failed":       0,
            "recipients":   0,
            "success":      False,
            "error":        msg,
        }

    logger.info(
        "✅  Risk check PASSED (green_light=True). Dispatching to %d recipients…",
        len(recipients),
    )

    # ── Step 3: Build email content ───────────────────────────────────────────
    subject   = content_dict.get("email_subject", f"Campaign #{campaign_id} — Important Update")
    html_body = _build_html_body(content_dict, campaign_id)
    text_body = _build_text_body(content_dict)

    # ── Step 4: Send ──────────────────────────────────────────────────────────
    send_result = send_smtp_email(
        recipients=recipients,
        subject=subject,
        html_body=html_body,
        text_body=text_body,
        campaign_id=campaign_id,
    )

    # ── Step 5: Return summary ────────────────────────────────────────────────
    summary = {
        "blocked":      False,
        "block_reason": None,
        "sent":         len(send_result.get("sent", [])),
        "failed":       len(send_result.get("failed", [])),
        "recipients":   send_result.get("total", len(recipients)),
        "success":      send_result.get("success", False),
    }

    if summary["failed"] > 0:
        summary["failed_details"] = send_result.get("failed", [])
        logger.warning(
            "⚠️   Campaign %s: %d failed out of %d",
            campaign_id, summary["failed"], summary["recipients"],
        )

    return summary


# ── Manual test ────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    # Test 1: Blocked by risk
    dummy_content = {
        "email_subject": "Exclusive Sale — 50% OFF!",
        "email_body":    "Buy now before the offer expires.",
        "instagram_caption": "Flash sale! #SaaS #Deals",
        "twitter_post":      "🔥 50% OFF — Limited time. Click now!",
    }

    blocked_risk = {
        "green_light": False,
        "brand_safety": 3,
        "legal_risk": 7,
        "cultural_sensitivity": 4,
        "flag_reason": "Brand safety score below threshold (3/10)",
    }

    result = dispatch_campaign_email(dummy_content, campaign_id=1, risk_result=blocked_risk)
    print("\n── Test 1 (should be BLOCKED) ──────────────────────────")
    print(json.dumps(result, indent=2))

    # Test 2: Green light — will actually try to send if credentials are set
    passed_risk = {
        "green_light": True,
        "brand_safety": 9,
        "legal_risk": 9,
        "cultural_sensitivity": 9,
        "flag_reason": None,
    }

    result2 = dispatch_campaign_email(dummy_content, campaign_id=2, risk_result=passed_risk)
    print("\n── Test 2 (green light — will attempt SMTP send) ────────")
    print(json.dumps(result2, indent=2))
